name: Build and Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
                  known_hosts: "just-a-placeholder-so-we-dont-get-errors"

            - name: Adding Known Hosts
              run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

            - name: Deploy to EC2 instance
              run: ssh ubuntu@${{ secrets.SSH_HOST }} 'cd /home/ubuntu/typing-website/deployment && bash deploy.sh'
